### ISSUE TITLE
Possibility to add user info to crash information?

### ISSUE THREAD

**Issue by nachoBonafonte** [microsoft/plcrashreporter#121]
**Describe the solution you'd like**
I would like to have the possibility to add some custom information to the crash reporter so it can be saved in the crash report and recovered later as a property of PLCrashReport.

**Describe alternatives you've considered**
I thought about using crash callback with an arbitrary context but it has the problem that cannot be modified once crash reporter is enabled and  it would need to save that information in a separate file needing to handle separately.

**Additional context**
The idea is to keep extra information about what was happening in the app when the crash happened.

**Comment by MatkovIvan** [comment]
Hi @nachoBonafonte 👋 

Thanks for getting in touch! Yes, this one makes sense. Actually, we'd love to have it for [App Center](https://github.com/microsoft/appcenter-sdk-apple) too. No ETA though.

Currently workaround using crash callback is achievable: just put pointer to some storage instead of data directly to be able to modify it later.

**Comment by nachoBonafonte** [comment]
resolved in #124
