### ISSUE TITLE
Wrong path of LICENSE file on .podspec

### ISSUE THREAD

**Issue by taehoon-jung** [microsoft/plcrashreporter#146]
### **Description**

```
[!] Unable to read the license file `LICENSE.txt` for the spec `PLCrashReporter (1.7.2)`
```

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Please check path of LICNESE on `.podspec`.

- https://github.com/microsoft/plcrashreporter/blob/master/PLCrashReporter.podspec
- https://github.com/microsoft/plcrashreporter/blob/1.7.2/PLCrashReporter.podspec
```
  spec.license     = { :type => 'MIT', :file => 'LICENSE.txt' }
```

**Comment by MatkovIvan** [comment]
Hi @taehoon-jung,

`lint` check is performed each time before release. This path is (and should be) relative to release archive contents, not to repo root. You are probably trying to run `pod lib lint` instead of `pod spec lint`. If so it's expected that this file has different path locally, but it should be fine for release archive

**Comment by taehoon-jung** [comment]
@MatkovIvan It occurred from local cache
```
» pod cache clean PLCrashReporter
1: PLCrashReporter v1.7.2 (External)
2: PLCrashReporter v1.7.2 (Release)
Which pod cache do you want to remove?
```
I don't know why it occurred. I solved it after cleaning the cache.
Thank you! :)
