### ISSUE TITLE
v1.2 download is no longer available with cocoapod

### ISSUE THREAD

**Issue by reneeichhorn** [microsoft/plcrashreporter#178]
### **Description**

The specified source url for the cocoapod release https://github.com/CocoaPods/Specs/blob/master/Specs/9/5/4/PLCrashReporter/1.2.0/PLCrashReporter.podspec.json is no longer a valid url and causes all builds that still refer to the old version to fail.

### **Repro Steps**

Try to install version 1.2 via pod cli.

**Comment by MatkovIvan** [comment]
Hi @reneeichhorn,

It was already discussed in #46, #48, #49, #54. Since then, we contacted [the pod](https://cocoapods.org/pods/PLCrashReporter) owner and get ownership of it. The fixed version was released a while ago.
Please note that CocoaPods does NOT allow change anything in already released versions.
Not sure why do you need version 1.2 which does not contain the required slices for modern Xcode/devices/etc, so I highly recommend you update it.
