### ISSUE TITLE
Protobuf used in PLCrashreporter has CVSS Vulnerability

### ISSUE THREAD

**Issue by naveenkumart28** [microsoft/plcrashreporter#18]
Summary:
PLCrashReporter uses ProtoBuf 2.0
There is a reported security vulnerability which can be seen here,
https://nvd.nist.gov/vuln/detail/CVE-2015-5237
As Per https://bugzilla.redhat.com/show_bug.cgi?id=1256426, this vulnerability is fixed in protobuf ≥ 3.6.1

Is it possible to upgrade PLCrashReporter to use ProtoBuf 3.6.?
It seems, it will include changes in .proto files also to use ProtoBuf V3.

**Comment by MatkovIvan** [comment]
Hi there. The fix has been merged into `master`

**Comment by ozzyremi** [comment]
Hi @MatkovIvan, 

How are we supposed to deal with protobuf binary? Are we supposed to download ourself and put into binary location because I am getting following error while building: 
**error: Build input file cannot be found: '/Users/username/Downloads/plcrashreporter-master 2/Dependencies/protobuf-c/protobuf-c/protobuf-c.c' (in target 'CrashReporter-MacOSX-Static' from project 'CrashReporter')**

**Comment by danielpunkass** [comment]
@ozzyremi It looks like protobuf is listed in the Git submodules for the project. So you want to do a "git submodule update --init" I think, to get the files checked out.

**Comment by ozzyremi** [comment]
@danielpunkass  Thank you. It worked!!

**Comment by MatkovIvan** [comment]
Hi @ozzyremi ,

As mentioned above it's a git submodule. This change is also described in [readme](https://github.com/microsoft/plcrashreporter#checking-out-the-repository) and [changelog](https://github.com/microsoft/plcrashreporter/blob/master/CHANGELOG.md)

**Comment by MatkovIvan** [comment]
The fix is available in 1.4.0
