### ISSUE TITLE
The crash message could not be caught on my macOS Big Sur 11.3.1

### ISSUE THREAD

**Issue by fengshanlangzi** [microsoft/plcrashreporter#180]
I configured the AppDelegate correctly following the tutorial and open sanbox support,
my app was stuck when call "if ([crashReporter hasPendingCrashReport]) {" in Appdelage.m

```
PLCrashReporterConfig *config = [[PLCrashReporterConfig alloc] initWithSignalHandlerType: PLCrashReporterSignalHandlerTypeMach
                                                                   symbolicationStrategy: PLCrashReporterSymbolicationStrategyAll];
PLCrashReporter *crashReporter = [[PLCrashReporter alloc] initWithConfiguration: config];

// Enable the Crash Reporter.
NSError *error;
if (![crashReporter enableCrashReporterAndReturnError: &error]) {
    NSLog(@"Warning: Could not enable crash reporter: %@", error);
}

if ([crashReporter hasPendingCrashReport]) {.....
```

**Comment by DmitriyKirakosyan** [comment]
hi @fengshanlangzi 

Thank you for reaching out to us!
I will test your scenario and get back to you shortly!

**Comment by DmitriyKirakosyan** [comment]
Hi

Unfortunately, I could not reproduce the issue you described.

Please make sure you run the app in release mode and with no debugger attached. Otherwise PLCrashReporter will not able to catch crashes.

If it didn't help and you run the app without a debugger, can I ask you to provide more info about your environment? Xcode version, Mac type (M1 or Intel), method you use to integrate the library (cocoapods, spm)?
Please add more details about the issue you experienced. You said that your "app was stuck" on calling `hasPendingCrashReport`.
What did exactly happen. Did the app freeze or crash, or did the crash reporter return `false`?

Thanks.

**Comment by DmitriyKirakosyan** [comment]
We haven't heard from you for a while, so I'm closing this issue.

Please, feel free to reopen if the issue persists for you.
