### ISSUE TITLE
Filter the 0x0000000000000000 address

### ISSUE THREAD

**Issue by tamwei** [microsoft/plcrashreporter#193]
**Is your feature request related to a problem? Please describe.**
![1624513289](https://user-images.githubusercontent.com/13300832/123208565-ed65a300-d4f1-11eb-8a08-4d8e1337815e.png)
Sometimes this happens in the picture.
And I found that [KSCrash filtered 0x0000000000000000 addresses](https://github.com/kstenerud/KSCrash/blob/master/Source/KSCrash/Recording/Tools/KSStackCursor_Backtrace.c#L41),I don’t know if there is a better way.

I want to know if you are willing to fix this？Thank you

**Additional context**
MacOS
arm64 & x86_64

**Comment by tamwei** [comment]
In addition,I found another rare bug.
![1624519217](https://user-images.githubusercontent.com/13300832/123219659-b7c7b680-d4ff-11eb-9ee6-ff3f3d8bf2bf.png)
I noticed that this address is not in the range of Binary Images.

I guess [the undefined symbol may not be detected ?](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashAsyncMachOImage.c#L900)
or [The match imageList not include the image where this address is located?](https://github.com/microsoft/plcrashreporter/blob/master/Source/PLCrashReporter.m#L340)

 Of course, I don't know what the problem is. And This bug not appeared any more .

**Comment by russelarms** [comment]
Hi @tamwei, thanks for reaching out!
Is it possible for you to provide a sample project for this problem?

**Comment by tamwei** [comment]
For  0x0000000000000000 address( **0   ???                                 0x0000000000000000 0x0 + 0**)
I can reproduced it like this, Call abort() in the click event.
![1624614183](https://user-images.githubusercontent.com/13300832/123405890-e1a2db00-d5dc-11eb-9358-5cb57dac1dd4.png)


For the out range address   (**0   ???                                 0x00000001096402ab 0x0 + 0**)
I can't reproduce it now.

Thanks for your response。

**Comment by tamwei** [comment]
[TestForCrash.zip](https://github.com/microsoft/plcrashreporter/files/6715519/TestForCrash.zip)

This sample can reproduce the issue about 0x0000000000000000 address.

For the out range address (0 ??? 0x00000001096402ab 0x0 + 0)
I can't reproduce it now.

Thanks for your response.

**Comment by DmitriyKirakosyan** [comment]
Hi @tamwei,

Thank you for your sample!
Seeing 0x0000000000000000 in crash logs seems normal to me. It happens when there is no info found about that call.
In your example it happens in thread 8 which is not related to your crash and it is hard to say what was happening on that thread.
I don't see any reason in filtering such null addresses. Their presence indicates at least that something was happening at that point, which in some cases can help investigating the issue.

Regarding your second question. It is hard to tell without knowing specifics of your app and repro steps. Yes, this can happen if the image was not found/added. Do you use any dynamic libs linked in your app? There is a known issue that crashes happening in dynamic libs are not always properly symbolicating.
But again, it may be anything and for better understanding you would need more context about the crash scenario.

Please let me know if you have more questions.

**Comment by tamwei** [comment]
Got it,Thanks for your answer.
