### ISSUE TITLE
it doesn't work to update customData in PLCrashReporterCallbacks

### ISSUE THREAD

**Issue by jackieyk** [microsoft/plcrashreporter#249]
### **Description**

Please describe the issue you are facing using the SDK.
I tried to add some info to the crash report after crash happened, I used the PLCrashReporterCallbacks, modify the customData there. But I found the customData was not updated, it was still old value when I read the crash report when app started next time. 

### **Repro Steps**

Please list the steps used to reproduce your issue.
1.implement the PLCrashReporterCallbacks, add code to change customData there
2.make a crash
3.start app, read the customData from the reporter. the customData is not changed.

### **Details**

1. Which SDK version are you using?   【1.10.1】
2. Which OS version did you experience the issue on? 【iOS 15.5】
3. Which CocoaPods/Carthage/Xcode version are you using? 【Xcode13.2， Cocoapods1.11.2】 
4. What device version did you see this error on? Were you using an emulator or a physical device? 【iPhoneX】
5. What language are you using? 【swift】
    - [ ] Objective C
    - [*] Swift
6. What third party libraries are you using?

**Comment by MatkovIvan** [comment]
Hi @jackieyk,

Thanks for getting in touch!
It's expected - by design `PLCrashReporterCallbacks` calls after writing the crash to disk. Also, this callback has significant limitations, and cannot be considered as regular "on crash callback". Please read that doc for details:

https://github.com/microsoft/plcrashreporter/blob/81cdec2b3827feb03286cb297f4c501a8eb98df1/Source/CrashReporter.h#L213-L239

The same is for `customData` - it's by design that **it must be set before the crash**. The reasons are similar.
