### ISSUE TITLE
How to build a standalone protoc-c, like the previous v1.2 ?

### ISSUE THREAD

**Issue by xuning0** [microsoft/plcrashreporter#39]
I know the best way right now is to install protobuf-c with brew, but here I have to build it myself. I have tried to build according to protobuf-c's documentation, but I just got a **protoc-gen-c**. 

Then I renamed it to **protoc-c** and dragged it into the project to execute the command `--c_out="${DERIVED_FILES_DIR}/${CURRENT_ARCH}" "${INPUT_FILE_NAME}"`, which can also be executed. But it seems to depend on other libraries in my computer, it can't run independently on another computer.

**Comment by MatkovIvan** [comment]
Hi @xuning0,

Thanks for getting in touch!
Per protobuf-c's documentation
> protobuf-c requires a C compiler, a C++ compiler, protobuf, and pkg-config to be installed.

So, please make sure that all necessary dependencies are installed. Most likely it's due to lack of `protobuf` (without "-c").
Also, please consider to use binary distribution or follow documented way to build (via brew) to avoid such kind of problems.

Closing this because it's more a matter of `protoc-c` than PLCrashReporter.

**Comment by xuning0** [comment]
Hi @MatkovIvan ,
Thank you for your reply!

I would love to use "binary distribution" directly, but I can not find them. In the [release of protobuf-c](https://github.com/protobuf-c/protobuf-c/releases), there is only source code .zip. In the [release of protobuf](https://github.com/protocolbuffers/protobuf/releases), the closest thing is just protoc-version-platform.zip. 

Could you please tell me where to find the binary distribution of `protoc-c`? Thank you!

**Comment by MatkovIvan** [comment]
I meant binary distribution of PLCrashReporter. You can find it in GitHub release attachments - https://github.com/microsoft/plcrashreporter/releases/tag/1.4.0
For protobuf-c distribution questions I suggest you open issue in their repository.
