### ISSUE TITLE
iOS framework target doesn't work when included as workspace dependency on Xcode 11

### ISSUE THREAD

**Issue by erikr98** [microsoft/plcrashreporter#67]
I am looking into using this framework for my project and had tremendous difficulty getting it to work properly; in particular the compiler complained that the framework was bundled incorrectly. I noticed the iOS framework target is built by default using the MacOS 10.15 SDK; is this correct? When I changed this to iOS and rebuilt as an iOS-specific framework I was able to use it successfully. 

![Screen Shot 2020-04-20 at 12 24 17 PM](https://user-images.githubusercontent.com/3999154/79780945-56f08d00-8302-11ea-9b53-2e5105f51ea6.png)

Perhaps this is intentional, just wanted to point this out and see if I have done something wrong on my end. Thanks for building a great product, I'm looking forward to using it.

**Comment by MatkovIvan** [comment]
Hi @erikr98 ,

Thanks for getting in touch and pointing this out.
Yes, it was intentional before to get proper internal framework structure. This target is used just as a container for `lipo` script that packages static libraries into `.framework`. It doesn't compile any sources for this target, so it should not affect anything.
However, I reproduced this error on usage of this framework in the same workspace in Xcode 11. It worked well with Xcode 10, but it looks like Xcode 11 brings some additional checks for dependent targets.
Also, I want to note that it reproduces only if include framework that built from sources in the same workspace. Integrating with binaries that published in releases page works fine. So, I agree that the thing that we should address, but I don't think that it's a integration blocker for now.
