### ISSUE TITLE
No dynamic framework in release assets?

### ISSUE THREAD

**Issue by erkanyildiz** [microsoft/plcrashreporter#68]
On version 1.5.1 release assets I see these two zips:

```
PLCrashReporter-1.5.1.zip
PLCrashReporter-Static-1.5.1.zip
```
One of them has `-Static` stated explicitly. 
So, it gives me the impression that the other one is dynamic.

But when I checked the contents, I noticed that it is not:

```
mbp: iOS Framework/CrashReporter.framework$ file CrashReporter 
CrashReporter: Mach-O universal binary with 6 architectures: [arm_v7:current ar archive] [arm_v7s] [i386] [x86_64] [arm64] [arm64e]
CrashReporter (for architecture armv7):	current ar archive
CrashReporter (for architecture armv7s):	current ar archive
CrashReporter (for architecture i386):	current ar archive
CrashReporter (for architecture x86_64):	current ar archive
CrashReporter (for architecture arm64):	current ar archive
CrashReporter (for architecture arm64e):	current ar archive
```

Is this intentional?

**Comment by MatkovIvan** [comment]
Hi @erkanyildiz ,

Yes, it's intentional. We've added second (`-Static`) zip to provide static libraries (`.a`) instead of frameworks (`.framework`). The first zip format has not been changed for years: it contains dynamic framework for macOS and static ones for iOS and tvOS. Sorry for confusing names.
